// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

import System.Reflection;

[assembly: AssemblyVersion("3.2018.294.498")]
[assembly: AssemblyFileVersion("3.2018.294.498")]
